apiVersion: v1
kind: Namespace
metadata:
  name: zabbix
  labels:
    name: zabbix
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-proxy-sqlite3
  labels:
    app: zabbix
    tier: proxy
  namespace: zabbix
spec:
  replicas: 1
  selector:
      matchLabels:
        name: zabbix-proxy-sqlite3
  template:
    metadata:
      labels:
        name: zabbix-proxy-sqlite3
        app: zabbix
    spec:
      containers:
        - name: zabbix-proxy-sqlite3
          image: zabbix/zabbix-proxy-sqlite3:alpine-5.0-latest
          imagePullPolicy: Always
          ports:
          - containerPort: 10051
            protocol: TCP
            name: zabbix-trapper
          env:
          - name: ZBX_HOSTNAME
            value: "zabbix-proxy-sqlite3"
          - name: ZBX_CONFIGFREQUENCY
            value: "60"
          - name: ZBX_PROXYMODE
            value: "0"
          - name: ZBX_SERVER_HOST
            value: "{PUBLIC-IP}"
          - name: ZBX_SERVER_PORT
            value: "10051"